// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjprilxyygmnpvpqepwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcHJpbHh5eWdtbnB2cHFlcHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzk1ODEsImV4cCI6MjA2NTg1NTU4MX0.3NXz0FWw6-_eS8Kl5Nox7dyognngc29xRLk4yAd__A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);